dict1 = dict((('一月','正月'),('二月','花月')))
print(dict1)
dict1 = dict([['一月','正月'],['二月','花月']])
print(dict1)
dict2 = dict.fromkeys(('四月','五月'))
print(dict2)
dict2 = dict.fromkeys(['一月','四月'],'端月')
print(dict2)
print((dict1.keys()) )
print(tuple(dict1.values()))
print(list(dict1.items()) )
print(dict2.get('三月')) 
print(dict2)
print(dict2.setdefault('一月', '梅月')) 
print(dict2)
print(dict2.setdefault('三月', '梅月')) 
print(dict2)
dict1.update(dict2)
print(dict1)
dict1.pop('10月','NONE')
dict1.pop('四月')
print(dict1)
print(dict1.popitem())
dict1.clear() 
print(dict1)

